program: slurm/active/run_sweep_training_kikibouba_v1.sh
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  model.K:
    values: [1, 2, 4, 8, 16, 32, 64, 128]
project: kikibouba-v1-mop-clip
name: k_sweep_kikibouba_v1_multinode
command:
  - bash
  - slurm/active/run_sweep_training_kikibouba_v1.sh

