program: slurm/active/run_sweep_training_stanford_cars.sh
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  model.K:
    values: [1, 2, 4, 8, 16, 32, 64]
project: stanford-cars-mop-clip
name: k_sweep_stanford_cars_multinode
command:
  - bash
  - slurm/active/run_sweep_training_stanford_cars.sh

