program: slurm/active/run_sweep_training_subset_manzanita.sh
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  model.K:
    values: [1, 2, 4, 8, 16, 32, 64]  # 7 values: powers of 2
project: inat-subset-manzanita-mop-clip
name: k_sweep_subset_manzanita
command:
  - bash
  - slurm/active/run_sweep_training_subset_manzanita.sh

